### ISSUE TITLE
Unable to render rich display  Invalid PDF

### ISSUE THREAD

**Issue by Rnreck** [HuangRunHua/the-economist-time-etc#1]
Unable to render rich display

Invalid PDF
 the april .1.2023can not download

**Comment by HuangRunHua** [comment]
> Unable to render rich display
> 
> Invalid PDF the april .1.2023can not download

Hi there, which one can not be downloaded?

**Comment by Rnreck** [comment]
the economist 4.1.2023 can't be download before,but at this time i can download,it may be my network problems
