### ISSUE TITLE
thanks for your services,appreciate it,Could you please give me your TestFlight link,非常感谢 

### ISSUE THREAD

**Issue by youtubee30** [HuangRunHua/the-economist-time-etc#2]
thanks for your services,appreciate it,Could you please give me your TestFlight link,非常感谢

**Comment by HuangRunHua** [comment]
Could you give me your email? I will send link through email.Sent from my iPhoneOn Apr 22, 2023, at 11:25, youtubee30 ***@***.***> wrote:﻿
thanks for your services,appreciate it,Could you please give me your TestFlight link,非常感谢
